### ISSUE TITLE
🐋 MakeMKV does not 'start'

### ISSUE THREAD

**Issue by newhinton** [automatic-ripping-machine/automatic-ripping-machine#1545]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Does this issue exist in the latest version?

- [x] I'm using the latest release

### Describe the bug?

I have recently updated ARM, and set GID&UID to make it work properly on unraid.

Ever since, makemkv does not rip blurays anymore. (DVD's work)
It seems to start, but it never progresses to actually ripping the disc.

This is the debug output:

```
[09-01-2025 19:13:25] DEBUG ARM: arm_ripper.rip_visual_media Using MakeMKV: [True]
[09-01-2025 19:13:25] INFO ARM: arm_ripper.rip_visual_media ************* Ripping disc with MakeMKV *************
[09-01-2025 19:13:25] INFO ARM: makemkv.prep_mkv Updating MakeMKV key...
[09-01-2025 19:13:25] DEBUG ARM: makemkv.prep_mkv MAKEMKV_PERMA_KEY populated, using that...
[09-01-2025 19:13:25] DEBUG ARM: makemkv.prep_mkv Command Output for update_key.sh: ['/home/arm/.MakeMKV/settings.conf exists, updating value of app_Key']
[09-01-2025 19:13:25] INFO ARM: makemkv.makemkv Starting MakeMKV rip. Method is mkv
[09-01-2025 19:13:25] DEBUG ARM: makemkv.makemkv Storing new MakeMKV disc numbers to database.
[09-01-2025 19:13:26] DEBUG ARM: makemkv.run command: '/usr/local/bin/makemkvcon --robot --messages=-stdout info --cache=1 disc:9999'
[09-01-2025 19:13:26] DEBUG ARM: makemkv.run PID 261: command: '/usr/local/bin/makemkvcon --robot --messages=-stdout info --cache=1 disc:9999'
[09-01-2025 19:13:26] DEBUG ARM: makemkv.run MSG:1005,0,1,"MakeMKV v1.18.1 linux(x64-release) started","%1 started","MakeMKV v1.18.1 linux(x64-release)"
[09-01-2025 19:13:26] DEBUG ARM: makemkv.run MakeMKVMessage(code=1005, flags=0, count=1, message='MakeMKV v1.18.1 linux(x64-release) started', sprintf=['%1 started', 'MakeMKV v1.18.1 linux(x64-release)'])
```

Running `/usr/local/bin/makemkvcon --robot --messages=-stdout info --cache=1 disc:9999` manually yields:

```
# /usr/local/bin/makemkvcon --robot --messages=-stdout info --cache=1 disc:9999
MSG:1005,0,1,"MakeMKV v1.18.1 linux(x64-release) started","%1 started","MakeMKV v1.18.1 linux(x64-release)"
MSG:3338,0,2,"Downloading latest SDF to /root/.MakeMKV ...","Downloading latest %1 to %2 ...","SDF","/root/.MakeMKV"
```

and on a second run only:

```
# /usr/local/bin/makemkvcon --robot --messages=-stdout info --cache=1 disc:9999
MSG:1005,0,1,"MakeMKV v1.18.1 linux(x64-release) started","%1 started","MakeMKV v1.18.1 linux(x64-release)"
```

Do you know what the issue could be? Thanks!

### To Reproduce

No particular steps.

### Built from source files ?

- [ ] I Built the image from source

### What architecture are you seeing the problem on?

amd64

### Expected behavior?

Properly ripping the disc.

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by newhinton** [comment]
I still don't know why it wouldn't work, but after killing and recreating everything (including the database&co.) i finally got it to work again. A clean start did it in the end.

**Comment by newhinton** [comment]
Nevermind, it is just fixed for DVD's. Blurays are still stuck.

**Comment by dros-dev** [comment]
I had the same problem I think, for me it was related to makeMkv not working properly on linux after version 1.17.7 (see [here](https://forum.makemkv.com/forum/viewtopic.php?f=3&t=37670)) 
So I fixed it by changing makemkv version in `/install_makemkv.sh` (you also need to add an `/old` into the makemkv urls after `/download`) and running it manually after that you need to insert a disc once so makemkv runs and does a firmware dump. With this dump it works with the newer version as well. hope this helps :)
ps: @microtechno9000 while this issue persits with makemkv we could maybe add an info section to the readme, as this is really hard to debug because there is no log from makemkv whatsoever

**Comment by 1337-server** [comment]
```
root@355833e4195b:/home/arm# /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0
[2025-10-04 11:50:42,652] INFO ARM: __init__.<module> Setting log level to: DEBUG
[2025-10-04 11:50:42,652] DEBUG ARM: __init__.<module> Disable Login: False
[2025-10-04 11:50:42,652] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2025-10-04 11:50:42,671] DEBUG ARM: utils.arm_alembic_get Alembic Head is: a79af75f4b31
[2025-10-04 11:50:42,678] DEBUG ARM: utils.arm_db_get Database Head is: a79af75f4b31
[2025-10-04 11:50:42,678] DEBUG ARM: utils.arm_db_check Database is current. Head: a79af75f4b31DB: a79af75f4b31
[2025-10-04 11:50:42,680] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x75b7c48d3ac0>) (save_remote_images=True) (language=en) (id=1) (database_limit=200) (bootstrap_skin=spacelab) (use_icons=True) (index_refresh=2000) (notify_refresh=6500) 
[2025-10-04 11:50:42,681] DEBUG ARM: utils.arm_alembic_get Alembic Head is: a79af75f4b31
[2025-10-04 11:50:42,694] DEBUG ARM: utils.arm_db_get Database Head is: a79af75f4b31
[2025-10-04 11:50:42,694] DEBUG ARM: utils.arm_db_check Database is current. Head: a79af75f4b31DB: a79af75f4b31
[2025-10-04 11:50:42,694] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x75b7c48d3ac0>) (save_remote_images=True) (language=en) (id=1) (database_limit=200) (bootstrap_skin=spacelab) (use_icons=True) (index_refresh=2000) (notify_refresh=6500) 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 151, in <module>
    drive = SystemDrives.query.filter_by(mount=devpath).one()  # unique mounts
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2797, in one
    return self._iter().one()  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1827, in one
    return self._only_one_row(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 760, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required
root@355833e4195b:/home/arm# /usr/bin/python3 /opt/arm/arm/ripper/main.py -d /dev/sr0
[2025-10-04 12:08:01,354] INFO ARM: __init__.<module> Setting log level to: DEBUG
[2025-10-04 12:08:01,354] DEBUG ARM: __init__.<module> Disable Login: False
[2025-10-04 12:08:01,354] DEBUG ARM: __init__.<module> Debugging pin: 12345
[2025-10-04 12:08:01,375] DEBUG ARM: utils.arm_alembic_get Alembic Head is: a79af75f4b31
[2025-10-04 12:08:01,382] DEBUG ARM: utils.arm_db_get Database Head is: a79af75f4b31
[2025-10-04 12:08:01,382] DEBUG ARM: utils.arm_db_check Database is current. Head: a79af75f4b31DB: a79af75f4b31
[2025-10-04 12:08:01,383] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f3b5869ec20>) (save_remote_images=True) (language=en) (id=1) (database_limit=200) (bootstrap_skin=spacelab) (use_icons=True) (index_refresh=2000) (notify_refresh=6500) 
[2025-10-04 12:08:01,385] DEBUG ARM: utils.arm_alembic_get Alembic Head is: a79af75f4b31
[2025-10-04 12:08:01,399] DEBUG ARM: utils.arm_db_get Database Head is: a79af75f4b31
[2025-10-04 12:08:01,399] DEBUG ARM: utils.arm_db_check Database is current. Head: a79af75f4b31DB: a79af75f4b31
[2025-10-04 12:08:01,399] DEBUG ARM: utils.arm_db_cfg UISettings: (_sa_instance_state=<sqlalchemy.orm.state.InstanceState object at 0x7f3b5869ec20>) (save_remote_images=True) (language=en) (id=1) (database_limit=200) (bootstrap_skin=spacelab) (use_icons=True) (index_refresh=2000) (notify_refresh=6500) 
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 151, in <module>
    drive = SystemDrives.query.filter_by(mount=devpath).one()  # unique mounts
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2797, in one
    return self._iter().one()  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1827, in one
    return self._only_one_row(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 760, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required
root@355833e4195b:/home/arm# /usr/bin/python3 /opt/arm/arm/ripper/main.py -d /dev/sr0
```

This might be related, currently having the same issue. I dug into running it manually and checking the database. it looks like in some conditions none of the drives will be saved to the database. This ends up killing the run.

**Comment by 1337-server** [comment]
This I believe was caused by an old version of MakeMKV as the newer versions are only required for Blu-ray and UHD backups.  Going to close this as I believe this should now be resolved with https://github.com/automatic-ripping-machine/automatic-ripping-machine/pull/1588

**Comment by newhinton** [comment]
The latest release did not fix the issue with starting makemkv.

@dros-dev Your solution however, did work. It seems that the problem is makemkv later than 1.17.7.

**Comment by 1337-server** [comment]
Apologies for closing this early, I've reopened.

**Comment by Gaute2000** [comment]
Seems like I have the same issue. Fresh install with latest docker.
Problem with both DVD and BR

**Comment by ynnckvdv** [comment]
I also have this with both DVD and BR.
@dros-dev or @newhinton , could you explain where you exactly changed the `/install_makemkv.sh` script? Or maybe you don't use Docker? Thanks!

**Comment by aric49** [comment]
@ynnckvdv  - I also am encountering this issue on my own machine. It is quite frustrating.   I do concur with the group that this seems to be caused by an old version of MakeMKV.  I followed the advice by @dros-dev and tracked down the `install_makemkv.sh` script in the arm-dependencies repo and updated it to use MakeMKV 1.17.6.  I also went ahead and built my own forked version of the automatic-ripping-machine and pushed it to my Docker Hub.   This contains the old version of MakeMKV as well as the most recent version of ARM (2.20.5) at the time of writing. 

See if my forked image fixes your problem by using this image: [https://hub.docker.com/repository/docker/aric49/automatic-ripping-machine/tags](https://hub.docker.com/repository/docker/aric49/automatic-ripping-machine/tags)

You can update your Docker-Compose files, or docker run commands to use the image as follows: 

```sh
docker pull aric49/automatic-ripping-machine:2.20.5
``` 

If you want to have a peek at what changes I made, I pushed it to a quick and dirty GitHub repository: [https://github.com/aric49/arm-bug-fix](https://github.com/aric49/arm-bug-fix)


This is just a quick and dirty fix until the issue with MakeMKV gets resolved.  I don't plan on supporting this project long-term.   

I am curious, why isn't everyone having this issue? I couldn't get any recent version of ARM to run correctly on my setup before this fix.

**Comment by ynnckvdv** [comment]
@aric49  Thanks for helping out! I'm afraid I'm running into an issue with SQAlchemy with your image:

I ran your image with this:
```
docker run -d  
-p "8080:8080" \ 
-e ARM_UID="1000" \
-e ARM_GID="1000" \ 
-e TZ="Europe/Brussels"  \
-v "/home/arm/aric49-github/arm-bug-fix:/home/arm" \ 
-v "/home/arm/aric49-github/arm-bug-fix/music:/home/arm/music"
-v "/home/arm/aric49-github/arm-bug-fix/logs:/home/arm/logs" \  
-v "/home/arm/aric49-github/arm-bug-fix/media:/home/arm/media" \ 
-v "/home/arm/aric49-github/arm-bug-fix/config:/etc/arm/config" \ 
--device="/dev/sr0:/dev/sr0" \ 
--device="/dev/sr1:/dev/sr1" \
 --device="/dev/sr2:/dev/sr2" \ 
--device="/dev/sr3:/dev/sr3" \
 --device="/dev/sg0:/dev/sg0" \ 
--device="/dev/sg1:/dev/sg1" \
--device="/dev/sg2:/dev/sg2" \
 --device="/dev/sg3:/dev/sg3" \ 
--privileged \
--restart "always" \
--name "aric49-arm-rippers" \
 --cpuset-cpus='2,3' \
aric49/automatic-ripping-machine:2.20.5
```
Resulting in these logs:
```
arm@arm:~/aric49-github/arm-bug-fix$ docker logs -f arm-rippers
Starting web ui
Oct 26 12:04:00 05ae486ef7d3 cron[131]: (CRON) INFO (pidfile fd = 3)
Oct 26 12:04:00 05ae486ef7d3 cron[131]: (CRON) INFO (Running @reboot jobs)
[2025-10-26 12:04:01,105] INFO ARM: __init__.<module> Setting log level to: INFO
[2025-10-26 12:04:01,252] INFO ARM: utils.check_db_version No database found.  Initializing arm.db...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "DROP": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/arm/arm/runui.py", line 9, in <module>
    import arm.config.config as cfg  # noqa E402
  File "/opt/arm/arm/../arm/__init__.py", line 2, in <module>
    import arm.ripper
  File "/opt/arm/arm/../arm/ripper/__init__.py", line 3, in <module>
    from arm.ripper import logger, utils, makemkv, handbrake, identify, ARMInfo # noqa F401
  File "/opt/arm/arm/../arm/ripper/utils.py", line 24, in <module>
    from arm.ui import db  # needs to be imported before models
  File "/opt/arm/arm/../arm/ui/__init__.py", line 72, in <module>
    from arm.ui.database.database import route_database  # noqa: E402,F811
  File "/opt/arm/arm/../arm/ui/database/database.py", line 28, in <module>
    armui_cfg = ui_utils.arm_db_cfg()
  File "/opt/arm/arm/../arm/ui/utils.py", line 207, in arm_db_cfg
    check_db_version(cfg.arm_config['INSTALLPATH'], cfg.arm_config['DBFILE'])
  File "/opt/arm/arm/../arm/ui/utils.py", line 89, in check_db_version
    flask_migrate.upgrade(mig_dir)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 399, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "/opt/arm/arm/migrations/env.py", line 89, in <module>
    run_migrations_online()
  File "/opt/arm/arm/migrations/env.py", line 81, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/environment.py", line 937, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/opt/arm/arm/migrations/versions/2986d3f7ecf9_extended_optical_drive_info.py", line 21, in upgrade
    op.drop_column('system_drives', 'type')  # can be generated
  File "<string>", line 8, in drop_column
  File "<string>", line 3, in drop_column
  File "/usr/local/lib/python3.8/dist-packages/alembic/operations/ops.py", line 2273, in drop_column
    return operations.invoke(op)
  File "/usr/local/lib/python3.8/dist-packages/alembic/operations/base.py", line 393, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.8/dist-packages/alembic/operations/toimpl.py", line 89, in drop_column
    operations.impl.drop_column(
  File "/usr/local/lib/python3.8/dist-packages/alembic/ddl/impl.py", line 331, in drop_column
    self._exec(base.DropColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.8/dist-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1524, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "DROP": syntax error
[SQL: ALTER TABLE system_drives DROP COLUMN type]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```
Looks like the UI can't start, but it can with the same config with the official image. I have deleted the `/db` directory. To be sure I will start again with a clean VM later but I will expect the same result.

Any clue? Did your fix work for yourself? Thanks again!

**Comment by aric49** [comment]
@ynnckvdv  --  Strange that's happening to you.  I didn't see any issues like that on my end.  It just runs like it should.  Before uploading my code and making my original comment, I was able to successfully rip a DVD and a bluray disk on my end.   One big difference between my setup and your setup is that I'm using podman.  But honestly, the container runtime shouldn't matter.   I will try to re-create your `docker run` command on podman tonight to see if I can re-create your issue.   Off the top of my head, I have no idea why SQLAlchemy would have an issue since it would be creating the DB from scratch (assuming the DB doesn't already exist).   When I was troubleshooting this issue, I created and deleted the database file multiple times.   I will try to run your `docker run` command later this evening and I'll let you know if I'm able to re-create your issue or not.

**Comment by aric49** [comment]
@ynnckvdv  -- I checked again this evening and yes, I was able to re-create your issue when I pulled from my Docker Hub account.  The image I had cached locally worked, but the image on Docker Hub did not.   Just to be sure, I re-built the image fresh, tested it,  and pushed it back up to Docker Hub.  I then removed all my cached images, and pulled it fresh from Docker Hub.   It seems to be working now. My apologies, I think I may have accidentally pushed a prototype container before it was fully working.  It should be working now.  You may want to run a `docker rmi aric49/automatic-ripping-machine:2.20.5` to make sure you remove the old image from your local cache.

Here is my command:  (I tweaked your command slightly so that it removed the extra Disk drives, since I only have one, and I replaced `docker` with `podman`.  I'm also running with sudo, which is required for Podman)


```
sudo podman run -d \
-p 8080:8080 \
-e ARM_UID="1000" \
-e ARM_GID="1000" \
-e TZ="Europe/Brussels" \
-v "/home/aric/Development/GitHub/arm-bug-fix:/home/arm" \
-v "/home/aric/Development/GitHub/arm-bug-fix/music:/home/arm/music" \
-v "/home/aric/Development/GitHub/arm-bug-fix/logs:/home/arm/logs" \
-v "/home/aric/Development/GitHub/arm-bug-fix/media:/home/arm/media" \
-v "/home/aric/Development/GitHub/arm-bug-fix/config:/etc/arm/config" \
--device="/dev/sr0:/dev/sr0" \
--privileged \
--restart "always" \
--name "aric49-arm-rippers" \
--cpuset-cpus='2,3' \
aric49/automatic-ripping-machine:2.20.5
```


Here are the logs I get: 

```
sudo podman logs aric49-arm-rippers
*** Running /etc/my_init.d/10_syslog-ng.init...
Oct 29 03:56:45 2136087383f0 syslog-ng[8]: syslog-ng starting up; version='3.35.1'
*** Running /etc/my_init.d/arm_user_files_setup.sh...
Updating arm group id 1000 to default (1000)...
usermod: no changes
Updating arm group id 1000 to default (1000)...
Adding arm user to 'render' group
Checking ownership of /home/arm
[OK]: ARM UID and GID set correctly, ARM has access to '/home/arm' using 1000:1000
Removing any link between music and Music
Checking ownership of /etc/arm/config
[OK]: ARM UID and GID set correctly, ARM has access to '/etc/arm/config' using 1000:1000
Checking location of abcde configuration files
/etc/abcde.conf link doesnt exist
Setting ARM Timezone info: Europe/Brussels

Current default time zone: 'Europe/Brussels'
Local time is now:      Wed Oct 29 03:56:47 CET 2025.
Universal Time is now:  Wed Oct 29 02:56:47 UTC 2025.

*** Running /etc/my_init.d/start_udev.sh...
Trying to start udev
/etc/my_init.d/start_udev.sh: 0: can't access tty; job control turned off
udev Started successfully
# # # # # # 
*** Booting runit daemon...
*** Runit started as PID 129
Starting web ui
Oct 29 03:56:49 2136087383f0 cron[132]: (CRON) INFO (pidfile fd = 3)
Oct 29 03:56:49 2136087383f0 cron[132]: (CRON) INFO (Running @reboot jobs)
[2025-10-29 03:56:50,578] INFO ARM: __init__.<module> Setting log level to: INFO
[2025-10-29 03:56:50,919] INFO ARM: runui.<module> Starting ARM-UI on interface address - 10.88.0.9:8080
[2025-10-29 03:56:50,930] INFO ARM: runui.startup Updating Optical Drives
[2025-10-29 03:56:51,007] INFO ARM: wasyncore.log_info Serving on http://10.88.0.9:8080
[2025-10-29 03:57:42,108] ERROR ARM: auth.login No admin found
[2025-10-29 03:57:45,368] ERROR ARM: auth.login No admin found
[2025-10-29 03:57:49,313] ERROR ARM: auth.login No admin found
[2025-10-29 03:57:52,110] INFO ARM: settings.check_hw_transcode_support Handbrake call successful
```

Hope this helps. Let me know if I can assist any further.

**Comment by ynnckvdv** [comment]
@aric49 Yes! It's working again for me, thanks a lot!
I see some other people ran into it on #1539 , so we're not alone

**Comment by trevorhauter** [comment]
@aric49 Thanks for making this! I was having the same problem and this has helped me greatly while we wait for a fix

**Comment by Gaute2000** [comment]
Is this problem fixed in the latest release 2.21.0?

**Comment by Palleri** [comment]
> Is this problem fixed in the latest release 2.21.0?

I still have this issue with the latest release 2.21.0

**Comment by Love-Pengy** [comment]
> Is this problem fixed in the latest release 2.21.0?

No. I am currently running 2.21 and have the same issue

**Comment by Sono-Gomorrha** [comment]
I'm sorry, but is there an 'idiot guide' on how to pin the MakeMKV version to 1.17? 
I fail to understand how the interaction with the arm-dependencies repo happens. Maybe I'm having a 'stupid day', but it seems I'm not able to find something about this in the wiki.

Thanks a lot.

**Comment by ynnckvdv** [comment]
> I'm sorry, but is there an 'idiot guide' on how to pin the MakeMKV version to 1.17? 
> I fail to understand how the interaction with the arm-dependencies repo happens. Maybe I'm having a 'stupid day', but it seems I'm not able to find something about this in the wiki.
> 
> Thanks a lot.

I don't believe there is anything in the official ARM docs. You can have a look at the repo of @aric49, he made an ARM image with MakeMKV 1.17.  Check his comment with a working 'docker run' command up here: https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/1545#issuecomment-3459435657

**Comment by Sono-Gomorrha** [comment]
> > I'm sorry, but is there an 'idiot guide' on how to pin the MakeMKV version to 1.17?
> > I fail to understand how the interaction with the arm-dependencies repo happens. Maybe I'm having a 'stupid day', but it seems I'm not able to find something about this in the wiki.
> > Thanks a lot.
> 
> I don't believe there is anything in the official ARM docs. You can have a look at the repo of [@aric49](https://github.com/aric49), he made an ARM image with MakeMKV 1.17. Check his comment with a working 'docker run' command up here: [#1545 (comment)](https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/1545#issuecomment-3459435657)

Thanks... I did that.. now it is hanging at 'migrate database', which it says is successful and then just is stuck there. I honestly don't even care about the db and am fine with a new one.. but removing it also just repeats the same thing.. I think this is just not the day I will get this working again..

I know this is not the fault of arm and looks to be rooted in an issue of makemkv, but I'm really considering giving up on arm in total and rather find a way to connect my optical drive to my main computer and do the ripping semi-manually by directly running makemkv for movies/series and abcde for audio. I have a low volume of discs I rip and sometimes it feels like keeping the arm installation running is more work than doing it manually as I keep bumping into one issue after the other which results in workarounds (like having to run the drive in manual mode to be able to rip Bluray discs). 

I know this is most likely my personal problem and might be related to my hardware (I'm running this on an old PC for which I have no other use anymore), so it is really not meant as an attack on the devs. I still think the project is great when it works. It just does work too little for me these days, which is sad as I used it a lot in 2018 to initially rip all discs I had back then. 

Sorry for the offtopic comment, I felt I needed to express my frustration with the situation.

**Comment by buerviper** [comment]
I encounter the same problem as the original post, but already with a DVD, which is not working at all. CDs are working fine, so it is (I guess) the same makemkv problem mentioned before. Is there any ETA if and when this will be fixed in ARM? Until then, I will probably try and use @aric49's workaround (or just rip CDs until DVDs work for me lol).

I installed ARM using Docker if that's important.

```
[11-24-2025 08:31:04] INFO ARM: arm_ripper.rip_visual_media ************* Ripping disc with MakeMKV *************
[11-24-2025 08:31:04] INFO ARM: makemkv.prep_mkv Updating MakeMKV key...
[11-24-2025 08:31:05] DEBUG ARM: makemkv.prep_mkv Command Output for update_key.sh: ['MakeMKV beta key for this month:  ',>
[11-24-2025 08:31:05] INFO ARM: makemkv.makemkv Starting MakeMKV rip. Method is mkv
[11-24-2025 08:31:05] DEBUG ARM: makemkv.makemkv Storing new MakeMKV disc numbers to database.
[11-24-2025 08:31:05] DEBUG ARM: makemkv.run command: '/usr/local/bin/makemkvcon --robot --messages=-stdout info --cache=1 disc:9999'
[11-24-2025 08:31:05] DEBUG ARM: makemkv.run PID 23050: command: '/usr/local/bin/makemkvcon --robot --messages=-stdout info --cache=1 disc:9999'
[11-24-2025 08:31:05] DEBUG ARM: makemkv.run MSG:1005,0,1,"MakeMKV v1.18.2 linux(x64-release) started","%1 started","MakeMKV v1.18.2 linux(x64-release)"
[11-24-2025 08:31:05] DEBUG ARM: makemkv.run MakeMKVMessage(code=1005, flags=0, count=1, message='MakeMKV v1.18.2 linux(x64-release) started', sprintf=['%1 started', 'MakeMKV v1.18.2 linux(>
[11-24-2025 08:31:05] DEBUG ARM: makemkv.run MSG:3338,0,2,"Downloading latest SDF to /home/arm/.MakeMKV ...","Downloading latest %1 to %2 ...","SDF","/home/arm/.MakeMKV"
[11-24-2025 08:31:05] DEBUG ARM: makemkv.run MakeMKVMessage(code=3338, flags=0, count=2, message='Downloading latest SDF to /home/arm/.MakeMKV ...', sprintf=['Downloading latest %1 to %2 ..
```

**Comment by buerviper** [comment]
I can confirm that @aric49's workaround works, but it seems to have a couple of minor bugs (it showed my CPU as being used 100 % after initial setup). But it rips my DVDs now without any issue.

When I set this up, I encountered the same problem of db migration as @Sono-Gomorrha. I simply deleted all arm folders and did the setup from the beginning (with the docker compose file provided in #1542 this takes only few seconds fortunately). I hope this issue will be fixed in one of the coming ARM updates, I otherwise love the software a lot.

**Comment by onshisan** [comment]
I am also having this problem with the latest ARM docker (and MakeMKV 1.18.2). 

Strangely, while troubleshooting, I tried 6 different DVDs and 2 of them ripped successfully. I haven't been able to find a reason why the "lucky" two worked.

**Comment by NoSadBeHappy** [comment]
> [@ynnckvdv](https://github.com/ynnckvdv) - I also am encountering this issue on my own machine. It is quite frustrating. I do concur with the group that this seems to be caused by an old version of MakeMKV. I followed the advice by [@dros-dev](https://github.com/dros-dev) and tracked down the `install_makemkv.sh` script in the arm-dependencies repo and updated it to use MakeMKV 1.17.6. I also went ahead and built my own forked version of the automatic-ripping-machine and pushed it to my Docker Hub. This contains the old version of MakeMKV as well as the most recent version of ARM (2.20.5) at the time of writing.
> 
> See if my forked image fixes your problem by using this image: https://hub.docker.com/repository/docker/aric49/automatic-ripping-machine/tags
> 
> You can update your Docker-Compose files, or docker run commands to use the image as follows:
> 
> docker pull aric49/automatic-ripping-machine:2.20.5
> 
> If you want to have a peek at what changes I made, I pushed it to a quick and dirty GitHub repository: https://github.com/aric49/arm-bug-fix
> 
> This is just a quick and dirty fix until the issue with MakeMKV gets resolved. I don't plan on supporting this project long-term.
> 
> I am curious, why isn't everyone having this issue? I couldn't get any recent version of ARM to run correctly on my setup before this fix.

Thank you! Your fork worked perfect for me with multiple drives, as I had the same issue.

**Comment by aric49** [comment]
Glad to hear this fix is working for multiple folks. I've been ripping my own media using this fix.. Let me know if you have any questions/feedback. I haven't been checking Github very frequently due to the holidays.

**Comment by huskeyw** [comment]
[grench.log](https://github.com/user-attachments/files/24316891/grench.log)

I am not sure if I am having the smae bug or maybe related.. I updated arm yesterday. and at first it was exactly as others discribe, but I put two dvd's at once (two drives and suddenly it was working). but I have 1 dvd when it runs it gets past info, starts reading the disk, it does say "error reading media" but then contenues, but then locks the docker imiage up.. see MKV is still running, and shutting down docker fails.. on reboot it gives errors on diskid and takes about 15 min to reboot this ubuntu vm as its not shutting down, I did not find anyone having their sysetm lock up on a bad disk..

if I use other disk and I put  a disk in my blueray it hangs like everyone else, same part of the log ect.. then I put a second disk in my dvd player and they both start ripping. but if I just use the blueray it hangs..  so wierd..

**Comment by jkunczik** [comment]
I am experiencing the same issue. The forked docker image does not work for me. The crash occurs because of a database locking conflict and missing null-checki in the logging logic.

**1. The Root Cause: Database Locking**
My Container log shows a `sqlite3.OperationalError: database is locked`. (Not sure why, yet)

Because the database is locked, the transaction to store the mdisc fails and triggers a PendingRollbackError.

https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/5132031886f6c7d55343d600b56faa385f6265b8/arm/ripper/makemkv.py#L725-L732

**2. The Crash (TypeError)**
The ripper then proceeds to this line:

```
logging.info(f"MakeMKV disc number: {job.drive.mdisc:d}")
```

Since job.drive.mdisc is still None (was not set directly), the :d (integer) format specifier throws a TypeError. Python cannot format a NoneType as an integer.

**Comment by buerviper** [comment]
I now gave the most recent ARM version a try, because in the MakeMKV forum I read that the Linux compatibility has been restored in the recent versions. Unfortunately, that's not the case for me and MakeMKV still is stuck.

There are some additional new errors related to mounting of my drive, but I don't think they are related.

I made a completely new install using docker.

```
02-25-2026 06:34:21 ARM: INFO: ARM version: 2.22.1
02-25-2026 06:34:21 ARM: INFO: Python version: 3.10.12 (main, Jan 26 2026, 14:55:28) [GCC 11.4.0]
02-25-2026 06:34:21 ARM: INFO: User is: arm
02-25-2026 06:34:21 ARM: INFO: Alembic head is: 50d63e3650d2
02-25-2026 06:34:21 ARM: INFO: Database version is: 50d63e3650d2
02-25-2026 06:34:21 ARM: INFO: ************* Starting ARM processing at 2026-02-25 06:34:21.742588 *************
02-25-2026 06:34:22 ARM: INFO: Creating new job for drive.
02-25-2026 06:34:22 ARM: INFO: Looking for log files older than 1 days old.
02-25-2026 06:34:22 ARM: INFO: Checking path /home/arm/logs/ for old log files...
02-25-2026 06:34:22 ARM: INFO: Checking path /home/arm/logs/progress for old log files...
02-25-2026 06:34:22 ARM: INFO: Job: MVW
02-25-2026 06:34:22 ARM: INFO: Job #1 with PID 2522 is currently running.
02-25-2026 06:34:22 ARM: INFO: Starting Disc identification
02-25-2026 06:34:22 ARM: ERROR: Error while running command: ['findmnt', '--json', '/dev/sr0']
The command produced no output.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/ProcessHandler.py", line 26, in arm_subprocess
    arm_process = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['findmnt', '--json', '/dev/sr0']' returned non-zero exit status 1.
02-25-2026 06:34:22 ARM: INFO: Trying to mount disc at /dev/sr0...
02-25-2026 06:34:22 ARM: ERROR: Error while running command: ['mount', '--all', '-o', 'X-mount.mkdir', '/dev/sr0']
Output was: mount: /mnt/dev/sr0: must be superuser to use mount.
mount: /mnt/dev/sr1: must be superuser to use mount.
mount: /mnt/dev/sr2: must be superuser to use mount.
mount: /mnt/dev/sr3: must be superuser to use mount.
mount: /mnt/dev/sr4: must be superuser to use mount.
mount: /mnt/dev/sr5: must be superuser to use mount.
mount: /mnt/dev/sr6: must be superuser to use mount.
mount: /mnt/dev/sr7: must be superuser to use mount.
mount: /mnt/dev/sr8: must be superuser to use mount.
mount: /mnt/dev/sr9: must be superuser to use mount.
mount: /mnt/dev/sr10: must be superuser to use mount.
mount: /mnt/dev/sr11: must be superuser to use mount.
mount: /mnt/dev/sr12: must be superuser to use mount.
mount: /mnt/dev/sr13: must be superuser to use mount.
mount: /mnt/dev/sr14: must be superuser to use mount.
mount: /mnt/dev/sr15: must be superuser to use mount.
mount: /mnt/dev/sr16: must be superuser to use mount.
mount: /mnt/dev/sr17: must be superuser to use mount.
mount: /mnt/dev/sr18: must be superuser to use mount.
mount: /mnt/dev/sr19: must be superuser to use mount.
mount: /mnt/dev/sr20: must be superuser to use mount.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/ProcessHandler.py", line 26, in arm_subprocess
    arm_process = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mount', '--all', '-o', 'X-mount.mkdir', '/dev/sr0']' returned non-zero exit status 32.
02-25-2026 06:34:22 ARM: ERROR: Error while running command: ['findmnt', '--json', '/dev/sr0']
The command produced no output.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/ProcessHandler.py", line 26, in arm_subprocess
    arm_process = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['findmnt', '--json', '/dev/sr0']' returned non-zero exit status 1.
02-25-2026 06:34:22 ARM: ERROR: Disc was not and could not be mounted. Rip might fail.
02-25-2026 06:34:22 ARM: INFO: Disc identified as video
02-25-2026 06:34:22 ARM: ERROR: Pydvdid failed with the error: Path '' does not exist.
02-25-2026 06:34:24 ARM: INFO: Disc title Post ident -  title:MVW year:None video_type:unknown disctype: dvd
02-25-2026 06:34:24 ARM: INFO: We have no previous rips/jobs matching this label
02-25-2026 06:34:24 ARM: INFO: Waiting 60 seconds for manual override.
02-25-2026 06:35:24 ARM: INFO: ******************* Logging ARM variables *******************
02-25-2026 06:35:24 ARM: INFO: devpath: /dev/sr0
02-25-2026 06:35:24 ARM: INFO: mountpoint: 
02-25-2026 06:35:24 ARM: INFO: title: MVW
02-25-2026 06:35:24 ARM: INFO: year: None
02-25-2026 06:35:24 ARM: INFO: video_type: unknown
02-25-2026 06:35:24 ARM: INFO: hasnicetitle: False
02-25-2026 06:35:24 ARM: INFO: label: MVW
02-25-2026 06:35:24 ARM: INFO: disctype: dvd
02-25-2026 06:35:24 ARM: INFO: manual_start: False
02-25-2026 06:35:24 ARM: INFO: ******************* End of ARM variables *******************
02-25-2026 06:35:24 ARM: INFO: ******************* Logging config parameters *******************
02-25-2026 06:35:24 ARM: INFO: skip_transcode: False
02-25-2026 06:35:24 ARM: INFO: mainfeature: False
02-25-2026 06:35:24 ARM: INFO: minlength: 60
02-25-2026 06:35:24 ARM: INFO: maxlength: 99999
02-25-2026 06:35:24 ARM: INFO: videotype: auto
02-25-2026 06:35:24 ARM: INFO: manual_wait: True
02-25-2026 06:35:24 ARM: INFO: manual_wait_time: 60
02-25-2026 06:35:24 ARM: INFO: ripmethod: mkv
02-25-2026 06:35:24 ARM: INFO: mkv_args: 
02-25-2026 06:35:24 ARM: INFO: delrawfiles: True
02-25-2026 06:35:24 ARM: INFO: hb_preset_dvd: HQ 1080p30 Surround
02-25-2026 06:35:24 ARM: INFO: hb_preset_bd: HQ 1080p30 Surround
02-25-2026 06:35:24 ARM: INFO: hb_args_dvd: --audio-lang eng,deu,kor,jpn,fre,ita --all-audio --subtitle-lang-list eng,deu --all-subtitles --subtitle-burned="none"
02-25-2026 06:35:24 ARM: INFO: hb_args_bd: --audio-lang eng,deu,kor,jpn,fre,ita --all-audio --subtitle-lang-list eng,deu --all-subtitles --subtitle-burned="none"
02-25-2026 06:35:24 ARM: INFO: ffmpeg_cli: FFMPEG
02-25-2026 06:35:24 ARM: INFO: ffmpeg_local: FFMPEG
02-25-2026 06:35:24 ARM: INFO: use_ffmpeg: False
02-25-2026 06:35:24 ARM: INFO: ffmpeg_args: <not given>
02-25-2026 06:35:24 ARM: INFO: raw_path: /home/arm/media/raw/
02-25-2026 06:35:24 ARM: INFO: transcode_path: /home/arm/media/transcode/
02-25-2026 06:35:24 ARM: INFO: completed_path: /home/arm/media/completed/
02-25-2026 06:35:24 ARM: INFO: extras_sub: extras
02-25-2026 06:35:24 ARM: INFO: emby_refresh: False
02-25-2026 06:35:24 ARM: INFO: emby_server: 
02-25-2026 06:35:24 ARM: INFO: emby_port: 8096
02-25-2026 06:35:24 ARM: INFO: notify_rip: True
02-25-2026 06:35:24 ARM: INFO: notify_transcode: True
02-25-2026 06:35:24 ARM: INFO: max_concurrent_transcodes: 0
02-25-2026 06:35:24 ARM: INFO: max_concurrent_makemkvinfo: 0
02-25-2026 06:35:24 ARM: INFO: ******************* End of config parameters *******************
02-25-2026 06:35:24 ARM: INFO: Checking for fstab entry.
02-25-2026 06:35:24 ARM: INFO: fstab entry is: /dev/sr0  /mnt/dev/sr0  udf,iso9660  defaults,users,utf8,ro  0  0
02-25-2026 06:35:24 ARM: INFO: Final Output directory "/home/arm/media/transcode/unidentified/MVW"
02-25-2026 06:35:24 ARM: INFO: Final Output directory "/home/arm/media/completed/unidentified/MVW"
02-25-2026 06:35:24 ARM: INFO: Processing files to: /home/arm/media/transcode/unidentified/MVW
02-25-2026 06:35:24 ARM: INFO: ************* Ripping disc with MakeMKV *************
02-25-2026 06:35:24 ARM: INFO: Updating MakeMKV key...
02-25-2026 06:35:24 ARM: INFO: Starting MakeMKV rip. Method is mkv
```

**Comment by Raspberry32** [comment]
> [@ynnckvdv](https://github.com/ynnckvdv) - I also am encountering this issue on my own machine. It is quite frustrating. I do concur with the group that this seems to be caused by an old version of MakeMKV. I followed the advice by [@dros-dev](https://github.com/dros-dev) and tracked down the `install_makemkv.sh` script in the arm-dependencies repo and updated it to use MakeMKV 1.17.6. I also went ahead and built my own forked version of the automatic-ripping-machine and pushed it to my Docker Hub. This contains the old version of MakeMKV as well as the most recent version of ARM (2.20.5) at the time of writing.
> 
> See if my forked image fixes your problem by using this image: https://hub.docker.com/repository/docker/aric49/automatic-ripping-machine/tags
> 
> You can update your Docker-Compose files, or docker run commands to use the image as follows:
> 
> docker pull aric49/automatic-ripping-machine:2.20.5
> 
> If you want to have a peek at what changes I made, I pushed it to a quick and dirty GitHub repository: https://github.com/aric49/arm-bug-fix
> 
> This is just a quick and dirty fix until the issue with MakeMKV gets resolved. I don't plan on supporting this project long-term.
> 
> I am curious, why isn't everyone having this issue? I couldn't get any recent version of ARM to run correctly on my setup before this fix.

A question about this fork - is this pull supposed to supply all of the files I need to run ARM? When I pull, I can't seem to find anything in my arm/home/, like the start_arm_container.sh or .db files*. The latest image from the main isn't letting me rip so I'm looking for fixes, any help on understanding what I'm missing from the aric49 fork would be greatly appreciated!

**Comment by buerviper** [comment]
So after reading a bit on the MakeMKV board, I read this issue of MakeMKV not working on Linux might be related to the firmware of the disc player. I used the ultimate flashing guide from their forums and... ARM is working! 
https://forum.makemkv.com/forum/viewtopic.php?f=16&t=19634

Currently running 2.22.2.

**Comment by Raspberry32** [comment]
> So after reading a bit on the MakeMKV board, I read this issue of MakeMKV not working on Linux might be related to the firmware of the disc player. I used the ultimate flashing guide from their forums and... ARM is working! https://forum.makemkv.com/forum/viewtopic.php?f=16&t=19634
> 
> Currently running 2.22.2.

My understanding is firmware only really matters for Blu-ray drives, right? Standard DVD drives don't require firmware flashes?

Also, do you have any insight as to how to get the aric49 fork functioning? My pull completes but I don't receive any new config files or anything (see comment above). Maybe I'm misunderstanding the fork's true function...

**Comment by buerviper** [comment]
I can't tell you about DVD drives, unfortunately. I am using a BD drive, but had problems with both Blurays and DVDs.

The aric49fork just worked for me using Docker.

**Comment by ac19g12** [comment]
I seem to have the same issue, but only when mainfeature is false (or 0). Is anyone else finding this?

**Comment by trevorhauter** [comment]
@ac19g12 I have been having this issue for a long time now, my mainfeature is set to false but I have never had it on, so not sure if it's important. I've gotten around this by using aric49's fix above https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/1545#issuecomment-3440280657
