### ISSUE TITLE
CD are not idetified 

### ISSUE THREAD

**Issue by k0201** [automatic-ripping-machine/automatic-ripping-machine#380]
### Description
Hello, i have a vast collection o CDs and wanted to ripp them. I started with first 100 and half of them was not identified. I tried both cddb and musicbrainz and even cddb in arm.yaml file and musicbrainz in .abcde.conf with no luck. Sometimes the log files gets correct naming, but the ripped files are put in Unknown Artist folder. Is there any better config possibility to get better results? Or if not is it possible to break ripping when artist is not detected? 

### Log file;
I attach an output for the problem i described:
[Vangelis_El_Greco.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5726299/Vangelis_El_Greco.log)

**Comment by 1337-server** [comment]
Did you edit the /home/arm/.abcde.conf ?

You must use `CDDBMETHOD=musicbrainz       # Use MusicBrainz for CDDB ` for discs to be identified 

ARM is correctly identifying the disc, but the ripper abcde is maybe not setup correctly.


here is my own .abcde.conf that i use


```
# -----------------$HOME/.abcde.conf----------------- #
# 
# A sample configuration file to convert music cds to 
#       FLAC using abcde version 2.7.2
# 
#       http://andrews-corner.org/abcde.html
# -------------------------------------------------- #
#
# This script was copied from the above site with the following modification:
#
# Set to non-interactive
# CDDMETHOD=cddb since it's more reliable (for my CDs)
# Enabled getalbumart
# Change output format from artist-album to artist/album

INTERACTIVE=n

# Encode tracks immediately after reading. Saves disk space, gives
# better reading of 'scratchy' disks and better troubleshooting of
# encoding process but slows the operation of abcde quite a bit:
#LOWDISK=y

# Specify the method to use to retrieve the track information,
# the alternative is to specify 'cddb':
CDDBMETHOD=musicbrainz       # Use MusicBrainz for CDDB 
ACTIONS=default,playlist,getalbumart,read,encode,tag,move,clean

# Make a local cache of cddb entries and then volunteer to use 
# these entries when and if they match the cd:
#CDDBCOPYLOCAL="y"
#CDDBLOCALDIR="$HOME/.cddb"
#CDDBLOCALRECURSIVE="y"
#CDDBUSELOCAL="y"

# Specify the encoder to use for FLAC. In this case
# flac is the only choice.
FLACENCODERSYNTAX=flac

# Specify the path to the selected encoder. In most cases the encoder
# should be in your $PATH as I illustrate below, otherwise you will 
# need to specify the full path. For example: /usr/bin/flac
FLAC=flac

# Specify your required encoding options here. Multiple options can
# be selected as '--best --another-option' etc.
# Overall bitrate is about 880 kbs/s with level 8.
FLACOPTS='-s -e -V -8' 

# Output type for FLAC.
OUTPUTTYPE="flac"

# The cd ripping program to use. There are a few choices here: cdda2wav,
# dagrab, cddafs (Mac OS X only) and flac. New to abcde 2.7 is 'libcdio'.
CDROMREADERSYNTAX=cdparanoia            
                                     
# Give the location of the ripping program and pass any extra options,
# if using libcdio set 'CD_PARANOIA=cd-paranoia'.
#CDPARANOIA=cdparanoia  
#CDPARANOIAOPTS="--never-skip=40"

# Give the location of the CD identification program:       
#CDDISCID=cd-discid            
                               
# Give the base location here for the encoded music files.
OUTPUTDIR="/home/arm/Music"                

# The default actions that abcde will take.
#ACTIONS=cddb,playlist,getalbumart,read,encode,replaygain,tag,move,clean
              
# Decide here how you want the tracks labelled for a standard 'single-artist',
# multi-track encode and also for a multi-track, 'various-artist' encode:
OUTPUTFORMAT='${OUTPUT}/${ARTISTFILE}/${ALBUMFILE}/${TRACKNUM}.${TRACKFILE}'
VAOUTPUTFORMAT='${OUTPUT}/Various Artists/${ALBUMFILE}/${TRACKNUM}.${ARTISTFILE}-${TRACKFILE}'

# Decide here how you want the tracks labelled for a standard 'single-artist',
# single-track encode and also for a single-track 'various-artist' encode.
# (Create a single-track encode with 'abcde -1' from the commandline.)
ONETRACKOUTPUTFORMAT='${OUTPUT}/${ARTISTFILE}/${ALBUMFILE}/${ALBUMFILE}'
VAONETRACKOUTPUTFORMAT='${OUTPUT}/Various Artists/${ALBUMFILE}/${ALBUMFILE}'

# Create playlists for single and various-artist encodes. I would suggest
# commenting these out for single-track encoding.
PLAYLISTFORMAT='${OUTPUT}/${ARTISTFILE}/${ALBUMFILE}/${ALBUMFILE}.m3u'
VAPLAYLISTFORMAT='${OUTPUT}/Various Artists/${ALBUMFILE}/${ALBUMFILE}.m3u'

# This function takes out dots preceding the album name, and removes a grab
# bag of illegal characters. It allows spaces, if you do not wish spaces add
# in -e 's/ /_/g' after the first sed command.
mungefilename ()
{
  echo "$@" | sed -e 's/^\.*//' | tr -d ":><|*/\"'?[:cntrl:]"
}

# What extra options?
MAXPROCS=4                              # Run a few encoders simultaneously
PADTRACKS=y                             # Makes tracks 01 02 not 1 2
EXTRAVERBOSE=2                          # Useful for debugging
COMMENT='abcde version 2.8.1'           # Place a comment...
EJECTCD=y                               # Please eject cd when finished :-)
```

**Comment by k0201** [comment]
Thanks for fast replay. The only line I changed earlier  in this file was CDDBMETHOD=musicbrainz, but it seams it was not enough. After copying and pasting from your file it seams to work for this CD. I will give more feedback after checking more.

**Comment by 1337-server** [comment]
Great to hear its working.

I think it was because of the line `ACTIONS=default,playlist,getalbumart,read,encode,tag,move,clean` it was previously still calling cddb instead of default (default=musicbrainz)

Musicbrainz is fantastic at recognizing CD's but it doesn't have every CD available. But you can help out by adding CD's that you know https://musicbrainz.org/ and that MB doesn't recognize.

As for exiting when a disc is not identified, this would be something that would need coding changes. If you would like to add the changes yourself the easiest way would be to change the main call in main.py
You should be looking for this
```
    elif job.disctype == "music":
        if utils.rip_music(job, logfile):
```

And you could change it to something like this

```
    elif job.disctype == "music":
        if job.hasnicetitle:
            if utils.rip_music(job, logfile):
                utils.notify(job, "ARM notification", "Music CD: " + str(job.label) + " processing complete. ")
                utils.scan_emby(job)
                ## This shouldnt be needed. but to be safe
                job.status = "success"
                db.session.commit()
            else:
                logging.info("Music rip failed.  See previous errors.  Exiting. ")
                job.eject()
                job.status = "fail"
                db.session.commit()
        else:
            utils.notify(job, "ARM notification", "Music CD: " + str(job.label) + " couldn't be identified. Exiting")
            logging.info("Music rip failed.  See previous errors.  Exiting. ")
            job.eject()
            job.status = "fail"
            db.session.commit()

```

**Comment by k0201** [comment]
Thanks! Look like it works perfectly, i will give more feedback when i will install more drives and check more then  CDs. It would be perfect to add skipping unknown files option to config file, and btw resolving #45 should prevent from problems like this in the future.

**Comment by k0201** [comment]
The problem I still get sometimes is that correct name is identified but parsing the data from musicbrainz is wrong:
`[2020-12-23 11:57:13] DEBUG ARM: musicbrainz._mb_request GET request for https://musicbrainz.org/ws/2/discid/0EXvGmAj5Zr7gkWyBMvHh6_CMn4-?inc=artist-credits
[2020-12-23 11:57:13] DEBUG ARM: musicbrainz._mb_request requesting with UA arm/v1.0 python-musicbrainzngs/0.7.1
[2020-12-23 11:57:13] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2020-12-23 11:57:13] INFO ARM: mbxml.parse_attributes in <ws2:artist>, uncaught attribute type-id
[2020-12-23 11:57:13] DEBUG ARM: getmusictitle.musicbrainz Infos: {'disc': {'id': '0EXvGmAj5Zr7gkWyBMvHh6_CMn4-', 'sectors': '207315', 'offset-list': [150, 19411, 43743, 59464, 87617, 106861, 130047, 160192, 161799, 168316, 172855, 182874, 188534, 198152], 'offset-count': 14, 'release-list': [{'id': 'f16d8420-2cf7-465f-bbfc-cd218b241828', 'title': 'Ice Cycles', 'status': 'Official', 'quality': 'normal', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': 'b79ac6e4-c486-40d7-bf83-432e818fc212', 'type': 'Group', 'name': 'Platypus', 'sort-name': 'Platypus'}}], 'date': '2000-03-14', 'country': 'US', 'release-event-list': [{'date': '2000-03-14', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'name': 'United States', 'sort-name': 'United States', 'iso-3166-1-code-list': ['US']}}], 'release-event-count': 1, 'barcode': '727701201122', 'asin': 'B00004R8QG', 'cover-art-archive': {'artwork': 'false', 'count': '0', 'front': 'false', 'back': 'false'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '0EXvGmAj5Zr7gkWyBMvHh6_CMn4-', 'sectors': '207315', 'offset-list': [150, 19411, 43743, 59464, 87617, 106861, 130047, 160192, 161799, 168316, 172855, 182874, 188534, 198152], 'offset-count': 14}, {'id': 'J3L6ABIHqvPOrs3.FKtfF5QVfSE-', 'sectors': '206217', 'offset-list': [150, 19357, 43524, 59236, 87203, 106152, 129182, 159096, 160703, 167220, 171759, 181778, 187438, 197056], 'offset-count': 14}], 'disc-count': 2, 'track-list': [], 'track-count': 14}], 'medium-count': 1, 'artist-credit-phrase': 'Platypus'}, {'id': '0d42d8c0-2638-43e9-b8cc-5bffb8e1803a', 'title': 'Ice Cycles', 'status': 'Official', 'quality': 'normal', 'packaging': 'Jewel Case', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'artist-credit': [{'artist': {'id': 'b79ac6e4-c486-40d7-bf83-432e818fc212', 'type': 'Group', 'name': 'Platypus', 'sort-name': 'Platypus'}}], 'date': '2000-03-06', 'country': 'XE', 'release-event-list': [{'date': '2000-03-06', 'area': {'id': '89a675c2-3e37-3518-b83c-418bad59a85a', 'name': 'Europe', 'sort-name': 'Europe', 'iso-3166-1-code-list': ['XE']}}], 'release-event-count': 1, 'barcode': '4001617319628', 'asin': 'B00004R9DQ', 'cover-art-archive': {'artwork': 'false', 'count': '0', 'front': 'false', 'back': 'false'}, 'medium-list': [{'position': '1', 'format': 'CD', 'disc-list': [{'id': '0EXvGmAj5Zr7gkWyBMvHh6_CMn4-', 'sectors': '207315', 'offset-list': [150, 19411, 43743, 59464, 87617, 106861, 130047, 160192, 161799, 168316, 172855, 182874, 188534, 198152], 'offset-count': 14}], 'disc-count': 1, 'track-list': [], 'track-count': 14}], 'medium-count': 1, 'artist-credit-phrase': 'Platypus'}], 'release-count': 2}}
[2020-12-23 11:57:13] ERROR ARM: getmusictitle.musicbrainz discid = 0EXvGmAj5Zr7gkWyBMvHh6_CMn4-
[2020-12-23 11:57:13] DEBUG ARM: getmusictitle.musicbrainz musicbrain works -  New title is Ice Cycles.  New Year is: 2000
[2020-12-23 11:57:13] DEBUG ARM: getmusictitle.musicbrainz artist=====Platypus
[2020-12-23 11:57:13] DEBUG ARM: getmusictitle.musicbrainz do have artwork?======false
**[2020-12-23 11:57:14] ERROR ARM: getmusictitle.musicbrainz Try 2 -  ERROR: 'NoneType' object has no attribute 'group**'`

**Comment by 1337-server** [comment]
That error means there was an a problem getting the cd cover art image.

Can you explain what details it got wrong ? I may have messed up the coding.

**Comment by k0201** [comment]
After changing this lines

**Comment by 1337-server** [comment]
Ahh thats easy to fix. the `job.hasnicetitle = True` is only set if the art cover is found.

you can edit getmusictitle.py and add it here 

```
        title = str(infos['disc']['release-list'][0]['title'])
        ##Set out release id as the CRC_ID
        job.crc_id = infos['disc']['release-list'][0]['id']
        job.hasnicetitle = True
        db.session.commit()
```

i had set the hasnicetitle too late(when getting cover art), it should have been set when it finds the musicbrainz entry. Ive fixed it now in my own repo. or you can make the changes manually.

**Comment by k0201** [comment]
Well this change stopped the app to work completely, i tried both changing manually and cloning from your v2.3_dev. The cd spins a little, but no log file or folder creation or eject is performed.

**Comment by 1337-server** [comment]
Can you try to run ```sudo -u arm /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0```  this should output what ever is wrong

**Comment by k0201** [comment]
The output is:
`Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 463, in <module>
    logging.basicConfig(filename="/home/arm/logs/NAS.log", format='[%(asctime)s] %(levelname)s ARM: %(message)s', datefmt='%Y-%m-%d %H:%M:%S', level="DEBUG")
  File "/usr/lib/python3.7/logging/__init__.py", line 1900, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/arm/logs/NAS.log'`

**Comment by 1337-server** [comment]
You will need to create a new file /home/arm/logs/NAS.log

I made some changes to try and have ARM use a single file for easier error reading. But this isn't fully implemented yet. 

The error is because ARM isn't yet setup to create this file it assumes(incorrectly) that this file already exists. Creating this file should fix the issue.

**Comment by k0201** [comment]
This problem is removed, is it still possible to use two drives with your dev2.3v ? I get following error:
[Laibach-Kapital.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/5749968/Laibach-Kapital.log)
> Traceback (most recent call last):
  File "/home/arm/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/arm/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

**Comment by 1337-server** [comment]
Yes its still supports more than one drive, however because of the changes i have made its no longer a good idea to start discs at the same time. They will need to be staggered 10-20 seconds should be long enough to ident the disc and update the database.

Im looking into various ways to get around this though.

This error can be an issue in the master branch of ARM, but the master branch of ARM only makes very limited requests to the database. And the chances of these happening at the same time are rare. But they can happen.

**Comment by k0201** [comment]
Thanks for answer! I did few tests of inserting second disc in different moments and it always hangs up on same moment i mentioned earlier, even when I insert the second disk when last track of first is ripped.

**Comment by 1337-server** [comment]
Ok ill look into this then

**Comment by 1337-server** [comment]
Ok  ive had a quick look into this and i think this my not be the same issue i was thinking. I think this issue is caused by my coding not correclty updating the database.

I thought this was the same as #311 but it seams to be a totally different issue. I've pushed some small changes to the getmusictitle.py that might fix the issue. I'll look into this more closely when i have more free time. If you could let me know if fixes the issue for you that would be great.

**Comment by k0201** [comment]
I will look at it in the morning and let you know :D

**Comment by 1337-server** [comment]
I took a deeper look into this, it was my coding not handling the db properly.

The latest commit should solve this, it now logs the error and continues. I'm working on a function to wait for the database to unlock and then update it. But this isnt fully built into it yet.

**Comment by charmarkk** [comment]
On these notes (and perhaps I missed something) - using the steps above to change over to MB was helpful and ID'd my CD! But the logs and notifications are still showing up as None_###.log. Something else afoot? Or did I indeed miss something?

**Comment by 1337-server** [comment]
> 
> 
> On these notes (and perhaps I missed something) - using the steps above to change over to MB was helpful and ID'd my CD! But the logs and notifications are still showing up as None_###.log. Something else afoot? Or did I indeed miss something?

Appolgies the user was using my own repo (i could tell because of the arm version number)

The master branch of arm needs alot of changes for it to work. You would need to manually make the changes from pull #373 for arm to work fully with music discs.

**Comment by charmarkk** [comment]
Aha, many thanks @1337-server! I'll have a look tomorrow and see what I can do. :) It seems to work okay enough, which is good for now!

**Comment by k0201** [comment]
Took me some time becouse my second dvd drive broke, but to the point simultaneous CD ripping doesnt work (it states databased locked when run from terminal), unless something changed in code during last 2 months. I also got some different error - I will put logs in new comments for clarity.

**Comment by k0201** [comment]
First one: ARM doestn chceck not supported signs in folder names in this example **/**
[colloseum.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6035176/colloseum.log)

**Comment by k0201** [comment]
And sometimes an error with parsing date or disk  happens
[Dzieci_z_Brodą.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6035187/Dzieci_z_Broda.log)
[The_Beatles-Sgt._Pepper's_Lonely_Hearts_Club_Band.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/6035188/The_Beatles-Sgt._Pepper.s_Lonely_Hearts_Club_Band.log)
