### ISSUE TITLE
🐛 Transcode Failing

### ISSUE THREAD

**Issue by ARMuser23** [automatic-ripping-machine/automatic-ripping-machine#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

MakeMKV succesfully backups up Blu-Ray then path seems to get skewed before transcode 

### To Reproduce

1. Insert Blu Ray
2. Wait for MakeMKV to complete.
3. Transcoding fails. 

### What OS are you seeing the problem on?

ubuntu-20.04

### ARM Release Version or Git hash (You can find this in the arm settings page)

v2.6.12

[TROLLS_WORLD_TOUR_167640243273(1).log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10736422/TROLLS_WORLD_TOUR_167640243273.1.log)

### Expected behavior?

Transcode process should carry on as expected. 

### Relevant log output

```shell
MSG:5072,131072,1,"Backing up disc into folder \"file:///home/arm/media/raw/Trolls-World-Tour_167640243273\"","Backing up disc into folder \"%1\"","file:///home/arm/media/raw/Trolls-World-Tour_167640243273"

[02-14-2023 19:59:56] INFO ARM: handbrake.handbrake_mkv Transcoding file CERTIFICATE to '/home/arm/media/transcode/movies/Trolls-World-Tour (2020)_167640243273/CERTIFICATE.mkv'
[02-14-2023 19:59:56] DEBUG ARM: handbrake.handbrake_mkv Sending command: nice HandBrakeCLI -i /home/arm/media/raw/Trolls-World-Tour_167640243273/CERTIFICATE -o '/home/arm/media/transcode/movies/Trolls-World-Tour (2020)_167640243273/CERTIFICATE.mkv' --preset "H.265 NVENC 2160p 4K" -E copy -a 1,2,3,4,5,6 --audio-copy-mask aac,ac3,eac3,dts,dtshd,mp3,flac --audio-fallback aac --all-subtitles --subtitle-burned=none >> /home/arm/logs/TROLLS_WORLD_TOUR_167640243273.log 2>&1
```

### Anything else?

There seems to be something broken between the MakeMKV steps as its missing from the log scanning for the main feature. If i manually enter the following commands then the transcode continues as expected

HandBrakeCLI -i '/home/arm/media/raw/Trolls-World-Tour-Dance-Party-Edition' -t 0 --scan

nice HandBrakeCLI -i '/home/arm/media/raw/Trolls-World-Tour-Dance-Party-Edition' -o '/home/arm/media/transcode/movies/Trolls-World-Tour-Dance-Party-Edition (2020)/Trolls.mkv' --main-feature --preset "H.265 NVENC 2160p 4K" -E copy -a 1,2,3,4,5,6 --audio-copy-mask aac,ac3,eac3,dts,dtshd,mp3,flac --audio-fallback aac --all-subtitles --subtitle-burned=none

Not sure if this is related to the fix that im currently running for #625 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
`CERTIFICATE to '/home/arm/media/transcode/movies/Trolls-World-Tour (2020)_167640243273/CERTIFICATE.mkv'`

I dont think thats a valid file ?

can you `ls -la` the raw directory ?

**Comment by ARMuser23** [comment]
Hi, correct that's not a valid file, the raw directory is listed as

 MSG:5072,131072,1,"Backing up disc into folder \"file:///home/arm/media/raw/Trolls-World-Tour_167640243273\"","Backing up disc into folder \"%1\"","file:///home/arm/media/raw/Trolls-World-Tour_167640243273" 

Im not sure why its then looking for /home/arm/media/transcode/movies/Trolls-World-Tour (2020)_167640243273/CERTIFICATE once it passes this into handbrake?

**Comment by 1337-server** [comment]
Are you using the same settings ? Can you provide the logs for the run from 2.6.0

This looks like it's because of the way the folder is passed into HandBrake.

MakeMKV/arm passes the entire folder into HandBrake, and it just runs over everything in the folder. 
`handbrake.handbrake_mkv` doesn't account for anything else non-video type being in the folder.

We will most likely need to add a check to `handbrake.handbrake_mkv` to only run against video files.
But this would also mean adding a move to final directory for everything else in the folder that's not videos.

**Comment by ARMuser23** [comment]
Logs for 2.6.0 attached below

[TROLLS_WORLD_TOUR_167647818773.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10766354/TROLLS_WORLD_TOUR_167647818773.log)

**Comment by 1337-server** [comment]
The only thing that changed with the backup command from now back to 2.6.0 was that it now forces the min length

2.6.0
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/158dc70a01635c63c062738877be8a03470eff6c/arm/ripper/makemkv.py#L57
2.6.12
https://github.com/automatic-ripping-machine/automatic-ripping-machine/blob/d849cc60342a0b202cc83ed86f8afa9fcd092176/arm/ripper/makemkv.py#L57

I can't really see that being the thing that causes the issue, but if you are able, would you mind changing that line 2.6.12 and seeing if it solves the issue ?

**Comment by 1337-server** [comment]
Can you continue the convo here ? @cmbernard333

Thank you for all of this. I think I managed to narrow it down.

I messed up the logic when I refactored main/arm_ripper

If possible, could you edit arm/ripper/arm_ripper.py and replace the `rip_with_mkv()` function with this
```
def rip_with_mkv(current_job, protection=0):
    """
    Test to check if title was or should be ripped by MakeMKV\n
    :param current_job: current job
    :param protection: If the disc have 99 track protection
    :return: Bool
    """
    mkv_ripped = False
    # Rip bluray
    if current_job.disctype == "bluray" and current_job.config.RIPMETHOD == "mkv":
        mkv_ripped = True
    # Rip dvd with mode: mkv and mainfeature: false
    if current_job.disctype == "dvd" and (not current_job.config.MAINFEATURE and current_job.config.RIPMETHOD == "mkv"):
        mkv_ripped = True
    # Rip dvds with skip transcode
    if current_job.disctype == "dvd" and current_job.config.SKIP_TRANSCODE:
        mkv_ripped = True
    # If dvd has 99 protection force MakeMKV to be used
    if protection and current_job.disctype == "dvd":
        mkv_ripped = True
    # if backup_dvd, always use mkv
    if current_job.config.RIPMETHOD == "backup_dvd":
        mkv_ripped = True
    return mkv_ripped
```

ARM shouldn't be using `handbrake.handbrake_mkv` for decrypted Blu-ray as that function is expecting only MKV files ready to be converted.
handbrake.handbrake_all is the correct catch-all for decrypted Blu-rays.

This should fix the issue. If it does, please let me know and ill submit a PR to fix it on main.

**Comment by cmbernard333** [comment]
> Can you continue the convo here ? @cmbernard333
> 
> Thank you for all of this. I think I managed to narrow it down.
> 
> I messed up the logic when I refactored main/arm_ripper
> 
> If possible, could you edit arm/ripper/arm_ripper.py and replace the `rip_with_mkv()` function with this
> 
> ```
> def rip_with_mkv(current_job, protection=0):
>     """
>     Test to check if title was or should be ripped by MakeMKV\n
>     :param current_job: current job
>     :param protection: If the disc have 99 track protection
>     :return: Bool
>     """
>     mkv_ripped = False
>     # Rip bluray
>     if current_job.disctype == "bluray" and current_job.config.RIPMETHOD == "mkv":
>         mkv_ripped = True
>     # Rip dvd with mode: mkv and mainfeature: false
>     if current_job.disctype == "dvd" and (not current_job.config.MAINFEATURE and current_job.config.RIPMETHOD == "mkv"):
>         mkv_ripped = True
>     # Rip dvds with skip transcode
>     if current_job.disctype == "dvd" and current_job.config.SKIP_TRANSCODE:
>         mkv_ripped = True
>     # If dvd has 99 protection force MakeMKV to be used
>     if protection and current_job.disctype == "dvd":
>         mkv_ripped = True
>     # if backup_dvd, always use mkv
>     if current_job.config.RIPMETHOD == "backup_dvd":
>         mkv_ripped = True
>     return mkv_ripped
> ```
> 
> ARM shouldn't be using `handbrake.handbrake_mkv` for decrypted Blu-ray as that function is expecting only MKV files ready to be converted. handbrake.handbrake_all is the correct catch-all for decrypted Blu-rays.
> 
> This should fix the issue. If it does, please let me know and ill submit a PR to fix it on main.

Here is the diff after I backed up `arm/ripper/arm_ripper.py`

```
root@e88106e05142:/opt/arm/arm/ripper# diff arm_ripper.py arm_ripper.py.bak
186c186
<     if current_job.disctype == "bluray" and current_job.config.RIPMETHOD == "mkv":
---
>     if current_job.disctype == "bluray":
195c195
<     if protection and current_job.disctype == "dvd":
---
>     if protection:
200c200,201
<     return mkv_ripped
---
>     return mkv_ripped
>
```

I re-ran arm and here is a log snippet 

```
Encoding: task 1 of 2, 27.68 % (0.00 fps, avg 0.00 fps, ETA 00h18m26s)
Encoding: task 1 of 2, 27.70 % (0.00 fps, avg 0.00 fps, ETA 00h18m25s)
Encoding: task 1 of 2, 27.72 % (0.00 fps, avg 0.00 fps, ETA 00h18m25s)
Encoding: task 1 of 2, 27.74 % (0.00 fps, avg 0.00 fps, ETA 00h18m24s)
Encoding: task 1 of 2, 27.75 % (0.00 fps, avg 0.00 fps, ETA 00h18m24s)
Encoding: task 1 of 2, 27.77 % (0.00 fps, avg 0.00 fps, ETA 00h18m24s)
Encoding: task 1 of 2, 27.78 % (0.00 fps, avg 0.00 fps, ETA 00h18m23s)
Encoding: task 1 of 2, 27.80 % (0.00 fps, avg 0.00 fps, ETA 00h18m23s)
Encoding: task 1 of 2, 27.82 % (0.00 fps, avg 0.00 fps, ETA 00h18m22s)
Encoding: task 1 of 2, 27.84 % (0.00 fps, avg 0.00 fps, ETA 00h18m22s)
Encoding: task 1 of 2, 27.86 % (0.00 fps, avg 0.00 fps, ETA 00h18m21s)
Encoding: task 1 of 2, 27.88 % (0.00 fps, avg 0.00 fps, ETA 00h18m21s)
Encoding: task 1 of 2, 27.89 % (0.00 fps, avg 0.00 fps, ETA 00h18m21s)
Encoding: task 1 of 2, 27.91 % (0.00 fps, avg 0.00 fps, ETA 00h18m20s)
Encoding: task 1 of 2, 27.92 % (0.00 fps, avg 0.00 fps, ETA 00h18m20s)
```

It appears to be working now. Will report back if issues come up.

**Comment by 1337-server** [comment]
Thanks for testing, that's good to hear that it seems to have fixed the issue.

I've pushed it to the 'nvidia' container, so if you want to continue testing 721 you should be able.

If this is still an issue, please let me know.

**Comment by cmbernard333** [comment]
Sorry to be a bother again - this pops up when I go to the arm settings page in the UI 

```



        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

'NoneType' object has no attribute 'status'
```

**Comment by 1337-server** [comment]
> Sorry to be a bother again - this pops up when I go to the arm settings page in the UI
> 
> ```
> 
> 
> 
>         \          SORRY            /
>          \                         /
>           \    This page does     /
>            ]   not exist yet.    [    ,'|
>            ]                     [   /  |
>            ]___               ___[ ,'   |
>            ]  ]\             /[  [ |:   |
>            ]  ] \           / [  [ |:   |
>            ]  ]  ]         [  [  [ |:   |
>            ]  ]  ]__     __[  [  [ |:   |
>            ]  ]  ] ]\ _ /[ [  [  [ |:   |
>            ]  ]  ] ] (#) [ [  [  [ :===='
>            ]  ]  ]_].nHn.[_[  [  [
>            ]  ]  ]  HHHHH. [  [  [
>            ]  ] /   `HH("N  \ [  [
>            ]__]/     HHH  "  \[__[
>            ]         NNN         [
>            ]         N/"         [
>            ]         N H         [
>           /          N            \
>          /           q,            \
>         /                           \
> 
> 'NoneType' object has no attribute 'status'
> ```

Please see #701

**Comment by cmbernard333** [comment]
> Thanks for testing, that's good to hear that it seems to have fixed the issue.
> 
> I've pushed it to the 'nvidia' container, so if you want to continue testing 721 you should be able.
> 
> If this is still an issue, please let me know.

Pulled latest image and tested a few other blu rays and I am seeing this issue. :( 

[THE_WORLDS_END_DOM.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10820499/THE_WORLDS_END_DOM.log)

**Comment by cmbernard333** [comment]
I updated the code locally:

```
def rip_with_mkv(current_job, protection=0):
    """
    Test to check if title was or should be ripped by MakeMKV\n
    :param current_job: current job
    :param protection: If the disc have 99 track protection
    :return: Bool
    """
    mkv_ripped = False
    # Rip bluray
    if current_job.disctype == "bluray" and current_job.config.RIPMETHOD in ["mkv","backup"]:
        mkv_ripped = True
    # Rip dvd with mode: mkv and mainfeature: false
    if current_job.disctype == "dvd" and (not current_job.config.MAINFEATURE and current_job.config.RIPMETHOD == "mkv"):
        mkv_ripped = True
    # Rip dvds with skip transcode
    if current_job.disctype == "dvd" and current_job.config.SKIP_TRANSCODE:
        mkv_ripped = True
    # If dvd has 99 protection force MakeMKV to be used
    if protection and current_job.disctype == "dvd":
        mkv_ripped = True
    # if backup_dvd, always use mkv
    if current_job.config.RIPMETHOD == "backup_dvd":
        mkv_ripped = True
    return mkv_ripped
 ```
 
And it fixed the issue above.

**Comment by 1337-server** [comment]
Thanks for testing this!

**Comment by ARMuser23** [comment]
still getting the same issue

MSG:1011,0,1,"Using LibreDrive mode (v01.0 id=388F93C712C1)","%1","Using LibreDrive mode (v01.0 id=388F93C712C1)"
MSG:5072,131072,1,"Backing up disc into folder \"file:///home/arm/media/raw/Chernobyl\"","Backing up disc into folder \"%1\"","file:///home/arm/media/raw/Chernobyl"
MSG:5085,0,0,"Loaded content hash table, will verify integrity of M2TS files.","Loaded content hash table, will verify integrity of M2TS files."
MSG:5070,128,0,"Backup done","Backup done"
MSG:5081,260,0,"Backup done.","Backup done."
DRV:1,0,999,0,"BD-RE PIONEER BD-RW   BDR-S12U 1.01 ALDL005989WL","","/dev/sr0"
[02-24-2023 10:46:36] DEBUG ARM: models.eject Unmounted disc /dev/sr1
[02-24-2023 10:46:39] DEBUG ARM: models.eject Failed to eject /dev/sr1
[02-24-2023 10:46:39] INFO ARM: makemkv.makemkv Exiting MakeMKV processing with return value of: /home/arm/media/raw/Chernobyl
[02-24-2023 10:46:39] DEBUG ARM: utils.database_adder Trying to add Notifications
[02-24-2023 10:46:39] DEBUG ARM: utils.database_adder successfully written Notifications to the database
[02-24-2023 10:46:39] INFO ARM: arm_ripper.rip_visual_media ************* Ripping with MakeMKV completed *************
[02-24-2023 10:46:39] DEBUG ARM: utils.database_updater status=transcoding:<class 'str'>
[02-24-2023 10:46:39] DEBUG ARM: utils.database_updater successfully written to the database
[02-24-2023 10:46:39] INFO ARM: arm_ripper.start_transcode ************* Starting Transcode With HandBrake *************
[02-24-2023 10:46:39] DEBUG ARM: arm_ripper.start_transcode handbrake_mkv: /home/arm/media/raw/Chernobyl, /home/arm/media/transcode/tv/Chernobyl (2019), /home/arm/logs/CHERNOBYL_DISC1_167723358835.log
[02-24-2023 10:46:39] DEBUG ARM: utils.sleep_check_process loop_count 2
[02-24-2023 10:46:39] INFO ARM: utils.sleep_check_process Starting A sleep check of HandBrakeCLI
[02-24-2023 10:46:39] DEBUG ARM: utils.sleep_check_process Number of Processes running is: 0 going to waiting 12 seconds.
[02-24-2023 10:46:39] INFO ARM: handbrake.handbrake_mkv Transcoding file BDMV to '/home/arm/media/transcode/tv/Chernobyl (2019)/BDMV.mkv'
[02-24-2023 10:46:39] DEBUG ARM: handbrake.handbrake_mkv Sending command: nice HandBrakeCLI -i /home/arm/media/raw/Chernobyl/BDMV -o '/home/arm/media/transcode/tv/Chernobyl (2019)/BDMV.mkv' --preset "Apple 2160p60 4K HEVC Surround" -E copy -a 1,2,3,4,5,6 --audio-copy-mask aac,ac3,eac3,dts,dtshd,mp3,flac --audio-fallback aac --all-subtitles --subtitle-burned=none >> /home/arm/logs/CHERNOBYL_DISC1_167723358835.log 2>&1
[10:46:39] hb_init: starting libhb thread
[10:46:39] thread 7f4bb3db9700 started ("libhb")
HandBrake 1.3.1 (2020032300) - Linux x86_64 - https://handbrake.fr
8 CPUs detected
Opening /home/arm/media/raw/Chernobyl/BDMV...
[10:46:39] CPU: Intel(R) Core(TM) i7-9700TE CPU @ 1.80GHz
[10:46:39]  - Intel microarchitecture Kaby Lake
[10:46:39]  - logical processor count: 8
[10:46:39] hb_scan: path=/home/arm/media/raw/Chernobyl/BDMV, title_index=1
disc.c:424: error opening file BDMV/index.bdmv
disc.c:424: error opening file BDMV/BACKUP/index.bdmv
bluray.c:2585: nav_get_title_list(/home/arm/media/raw/Chernobyl/BDMV/) failed
[10:46:39] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 6.0.1
libdvdread: Couldn't find device name.
libdvdread:DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[10:46:39] dvd: not a dvd - trying as a stream/file instead
[10:46:39] batch: scanning /home/arm/media/raw/Chernobyl/BDMV/MovieObject.bdmv
[10:46:39] hb_stream_open: open /home/arm/media/raw/Chernobyl/BDMV/MovieObject.bdmv failed
[10:46:39] libhb: scan thread found 0 valid title(s)
No title found.
HandBrake has exited.

[02-24-2023 10:46:39] ERROR ARM: handbrake.handbrake_mkv Handbrake encoding of file BDMV failed with code: 2(b'')
[02-24-2023 10:46:39] INFO ARM: handbrake.handbrake_mkv Transcoding file MAKEMKV to '/home/arm/media/transcode/tv/Chernobyl (2019)/MAKEMKV.mkv'
[02-24-2023 10:46:39] DEBUG ARM: handbrake.handbrake_mkv Sending command: nice HandBrakeCLI -i /home/arm/media/raw/Chernobyl/MAKEMKV -o '/home/arm/media/transcode/tv/Chernobyl (2019)/MAKEMKV.mkv' --preset "Apple 2160p60 4K HEVC Surround" -E copy -a 1,2,3,4,5,6 --audio-copy-mask aac,ac3,eac3,dts,dtshd,mp3,flac --audio-fallback aac --all-subtitles --subtitle-burned=none >> /home/arm/logs/CHERNOBYL_DISC1_167723358835.log 2>&1
[10:46:39] hb_init: starting libhb thread
[10:46:39] thread 7f7621d95700 started ("libhb")
HandBrake 1.3.1 (2020032300) - Linux x86_64 - https://handbrake.fr
8 CPUs detected
Opening /home/arm/media/raw/Chernobyl/MAKEMKV...
[10:46:39] CPU: Intel(R) Core(TM) i7-9700TE CPU @ 1.80GHz
[10:46:39]  - Intel microarchitecture Kaby Lake
[10:46:39]  - logical processor count: 8
[10:46:39] hb_scan: path=/home/arm/media/raw/Chernobyl/MAKEMKV, title_index=1

Scanning title 1 of 1, 0.00 %
Scanning title 1 of 1, 0.00 %
Scanning title 1 of 1, 0.00 %aacs.c:121: No usable AACS libraries found!
dec.c:197: aacs_open() failed: -1!
disc.c:424: error opening file BDMV/index.bdmv
disc.c:424: error opening file BDMV/BACKUP/index.bdmv
bluray.c:2585: nav_get_title_list(/home/arm/media/raw/Chernobyl/MAKEMKV/) failed
[10:46:40] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 6.0.1
libdvdread: Couldn't find device name.
libdvdread:DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[10:46:40] dvd: not a dvd - trying as a stream/file instead
[10:46:40] batch: scanning /home/arm/media/raw/Chernobyl/MAKEMKV/discattd.dat
[10:46:40] hb_stream_open: open /home/arm/media/raw/Chernobyl/MAKEMKV/discattd.dat failed
[10:46:40] libhb: scan thread found 0 valid title(s)
No title found.
HandBrake has exited.

[02-24-2023 10:46:40] ERROR ARM: handbrake.handbrake_mkv Handbrake encoding of file MAKEMKV failed with code: 2(b'')
[02-24-2023 10:46:40] INFO ARM: handbrake.handbrake_mkv Transcoding file CERTIFICATE to '/home/arm/media/transcode/tv/Chernobyl (2019)/CERTIFICATE.mkv'
[02-24-2023 10:46:40] DEBUG ARM: handbrake.handbrake_mkv Sending command: nice HandBrakeCLI -i /home/arm/media/raw/Chernobyl/CERTIFICATE -o '/home/arm/media/transcode/tv/Chernobyl (2019)/CERTIFICATE.mkv' --preset "Apple 2160p60 4K HEVC Surround" -E copy -a 1,2,3,4,5,6 --audio-copy-mask aac,ac3,eac3,dts,dtshd,mp3,flac --audio-fallback aac --all-subtitles --subtitle-burned=none >> /home/arm/logs/CHERNOBYL_DISC1_167723358835.log 2>&1
[10:46:40] hb_init: starting libhb thread
[10:46:40] thread 7f6bf3fd4700 started ("libhb")
HandBrake 1.3.1 (2020032300) - Linux x86_64 - https://handbrake.fr
8 CPUs detected
Opening /home/arm/media/raw/Chernobyl/CERTIFICATE...
[10:46:40] CPU: Intel(R) Core(TM) i7-9700TE CPU @ 1.80GHz
[10:46:40]  - Intel microarchitecture Kaby Lake
[10:46:40]  - logical processor count: 8
[10:46:40] hb_scan: path=/home/arm/media/raw/Chernobyl/CERTIFICATE, title_index=1
disc.c:424: error opening file BDMV/index.bdmv
disc.c:424: error opening file BDMV/BACKUP/index.bdmv
bluray.c:2585: nav_get_title_list(/home/arm/media/raw/Chernobyl/CERTIFICATE/) failed
[10:46:40] bd: not a bd - trying as a stream/file instead
libdvdnav: Using dvdnav version 6.0.1
libdvdread: Couldn't find device name.
libdvdread:DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdread:DVDOpenFilePath:findDVDFile /VIDEO_TS/VIDEO_TS.BUP failed
libdvdread: Can't open file VIDEO_TS.IFO.
libdvdnav: vm: failed to read VIDEO_TS.IFO
[10:46:40] dvd: not a dvd - trying as a stream/file instead
[10:46:40] batch: scanning /home/arm/media/raw/Chernobyl/CERTIFICATE/app.discroot.crt
[10:46:40] hb_stream_open: open /home/arm/media/raw/Chernobyl/CERTIFICATE/app.discroot.crt failed
[10:46:40] libhb: scan thread found 0 valid title(s)
No title found.
HandBrake has exited.

[02-24-2023 10:46:40] ERROR ARM: handbrake.handbrake_mkv Handbrake encoding of file CERTIFICATE failed with code: 2(b'')
[02-24-2023 10:46:40] INFO ARM: handbrake.handbrake_mkv Handbrake processing complete
[02-24-2023 10:46:40] DEBUG ARM: handbrake.handbrake_mkv

**Comment by 1337-server** [comment]
> still getting the same issue
 
```
# Rip bluray
if current_job.disctype == "bluray" and current_job.config.RIPMETHOD in ["mkv","backup"]:
```
Sorry, not sure what happened there, but that's not the code I posted.
This code works the exact same as the code already existing in the main repo. It treats `mkv` and `backup` rip types as the same. And they cannot be treated the same, or the backup versions will always fail.


Try this code

```
def rip_with_mkv(current_job, protection=0):
    """
    Test to check if title was or should be ripped by MakeMKV\n
    :param current_job: current job
    :param protection: If the disc have 99 track protection
    :return: Bool
    """
    mkv_ripped = False
    # Rip bluray
    if current_job.disctype == "bluray" and current_job.config.RIPMETHOD == "mkv":
        mkv_ripped = True
    # Rip dvd with mode: mkv and mainfeature: false
    if current_job.disctype == "dvd" and (not current_job.config.MAINFEATURE and current_job.config.RIPMETHOD == "mkv"):
        mkv_ripped = True
    # Rip dvds with skip transcode
    if current_job.disctype == "dvd" and current_job.config.SKIP_TRANSCODE:
        mkv_ripped = True
    # If dvd has 99 protection force MakeMKV to be used
    if protection and current_job.disctype == "dvd":
        mkv_ripped = True
    # if backup_dvd, always use mkv
    if current_job.config.RIPMETHOD == "backup_dvd":
        mkv_ripped = True
    return mkv_ripped
```

**Comment by ARMuser23** [comment]
i've applied the above, however no backup is being taken, it now goes straight to transcoding without using makemkv to make a backup.

**Comment by cmbernard333** [comment]
> > still getting the same issue
> 
> ```
> # Rip bluray
> if current_job.disctype == "bluray" and current_job.config.RIPMETHOD in ["mkv","backup"]:
> ```
> 
> Sorry, not sure what happened there, but that's not the code I posted. That code works the exact same as the code already existing in the main repo. It treats `mkv` and `backup` rip types as the same. And they cannot be treated the same, or the backup versions will always fail.
> 
> Try this code
> 
> ```
> def rip_with_mkv(current_job, protection=0):
>     """
>     Test to check if title was or should be ripped by MakeMKV\n
>     :param current_job: current job
>     :param protection: If the disc have 99 track protection
>     :return: Bool
>     """
>     mkv_ripped = False
>     # Rip bluray
>     if current_job.disctype == "bluray" and current_job.config.RIPMETHOD == "mkv":
>         mkv_ripped = True
>     # Rip dvd with mode: mkv and mainfeature: false
>     if current_job.disctype == "dvd" and (not current_job.config.MAINFEATURE and current_job.config.RIPMETHOD == "mkv"):
>         mkv_ripped = True
>     # Rip dvds with skip transcode
>     if current_job.disctype == "dvd" and current_job.config.SKIP_TRANSCODE:
>         mkv_ripped = True
>     # If dvd has 99 protection force MakeMKV to be used
>     if protection and current_job.disctype == "dvd":
>         mkv_ripped = True
>     # if backup_dvd, always use mkv
>     if current_job.config.RIPMETHOD == "backup_dvd":
>         mkv_ripped = True
>     return mkv_ripped
> ```

Sorry I should have been more specific when I posted. I was running into the exact same issue where it was going straight to using handbrake instead of calling makemkv. 

I looked at the code, and most likely wrongfully assumed, at the sequence of items and saw that `makemkv` was being called later. I looked at this line `current_job.disctype == "bluray" and current_job.config.RIPMETHOD == "mkv":` and saw that it was not referencing `backup`. The only other reference to `backup` I saw was in `makemkv` and that code won't be called without passing the `rip_with_mkv` check.

**Comment by 1337-server** [comment]
No, you were correct, my fix didn't work. And in fact made things worse in that it pushed Blu-rays right to HandBrake ignoring MakeMKV altogether.

I've reverted that locally and instead testing changing the start_transcode section. This seems to be the section causing issue

Changing
```
def start_transcode(job, logfile, hb_in_path, hb_out_path, protection):
    if rip_with_mkv(job, protection):
        # skip if transcode is disable
        if job.config.SKIP_TRANSCODE:
```
TO
```
def start_transcode(job, logfile, hb_in_path, hb_out_path, protection):
    if rip_with_mkv(job, protection) and job.config.RIPMETHOD == "mkv":
        # skip if transcode is disable
        if job.config.SKIP_TRANSCODE:
```

Still waiting for tests to finish. I'll update when it does.

**Comment by cmbernard333** [comment]
> No, you were correct, my fix didn't work. And in fact made things worse in that it pushed Blu-rays right to HandBrake ignoring MakeMKV altogether.
> 
> I've reverted that locally and instead testing changing the start_transcode section. This seems to be the section causing issue
> 
> Changing
> 
> ```
> def start_transcode(job, logfile, hb_in_path, hb_out_path, protection):
>     if rip_with_mkv(job, protection):
>         # skip if transcode is disable
>         if job.config.SKIP_TRANSCODE:
> ```
> 
> TO
> 
> ```
> def start_transcode(job, logfile, hb_in_path, hb_out_path, protection):
>     if rip_with_mkv(job, protection) and job.config.RIPMETHOD == "mkv":
>         # skip if transcode is disable
>         if job.config.SKIP_TRANSCODE:
> ```
> 
> Still waiting for tests to finish. I'll update when it does.

Will this support the backup + mkv path? I chiefly use `backup` as my ripping method.

**Comment by 1337-server** [comment]
Yes, ill break things down to try and explain what I meant to happen.

The first trigger in `arm_ripper.start_transcode` should be for the 'mkv' option only for both blu-ray and dvds.
So we are passing in the whole folder and every file in the folder should already be movie files.
```
    if rip_with_mkv(job, protection):
        # skip if transcode is disable
        if job.config.SKIP_TRANSCODE:
            logging.info("Transcoding is disabled, skipping transcode")
            return None
        logging.debug(f"handbrake_mkv: {hb_in_path}, {hb_out_path}, {logfile}")
        handbrake.handbrake_mkv(hb_in_path, hb_out_path, logfile, job)
```

#### This is for handbrake to scan any source DVD/Blu-ray decrypted etc. and find only the main file. Both `mkv` and `backup` can end up here depending on settings
```

    elif job.video_type == "movie" and job.config.MAINFEATURE and job.hasnicetitle:
        logging.debug(f"handbrake_main_feature: {hb_in_path}, {hb_out_path}, {logfile}")
        handbrake.handbrake_main_feature(hb_in_path, hb_out_path, logfile, job)
        job.eject()
```

#### This is the catch-all, this is telling handbrake there could be anything in this folder, scan and find video files and convert them. `backup` should be ending up in here.
```
    else:
        logging.debug(f"handbrake_all: {hb_in_path}, {hb_out_path}, {logfile}")
        handbrake.handbrake_all(hb_in_path, hb_out_path, logfile, job)
        job.eject()
    logging.info("************* Finished Transcode With HandBrake *************")
    utils.database_updater({'status': "active"}, job)
    return True
```


I'll need to redo it and add commenting.

But hopefully this should resolve the issue.

**Comment by cmbernard333** [comment]
Is this ready for testing? I can pull down an image or some code to test it out and see if it works out.

**Comment by 1337-server** [comment]
> Is this ready for testing? I can pull down an image or some code to test it out and see if it works out.

Yeah its ready for testing, Ive already submitted a PR (https://github.com/automatic-ripping-machine/automatic-ripping-machine/pull/757) so extra testing would be really helpful. Ive tested it a number of times and its seemed to go as planned.

The branch with the code is here: https://github.com/automatic-ripping-machine/automatic-ripping-machine/tree/728-transcode-failing

But if you prefer just pulling and running an image i pushed a build to dockerhub with this tag
`automaticrippingmachine/automatic-ripping-machine:728-transcode-failing`

**Comment by cmbernard333** [comment]
Ok tested and getting an error. 
[THE_WORLDS_END_DOM.log](https://github.com/automatic-ripping-machine/automatic-ripping-machine/files/10831932/THE_WORLDS_END_DOM.log)

Here is the telegram message that has some useful information as well.

```
[kepler.swordsnswagger.com] - ARM notification
ARM encountered a fatal error processing Jeff-Waynes-Musical-Version-of-the-War-of-the-Worlds-Alive-on-Stage-The-New-Generation. Check the logs for more details. 'int' object is not iterable
```

**Comment by 1337-server** [comment]
Thanks, it looks like you have set HandBrakeCLI to `/usr/local/bin/HandBrakeCLI` and that might be causing the issue

`returned non-zero exit status 127.` Means it cant find the HandBrakeCLI file in that location

**Comment by cmbernard333** [comment]
This seems to have fixed it. The image pulled down does not include the needed `nvidia` changes from the `automaticrippingmachine/automatic-ripping-machine:nvidia` image, but it no longer causes errors when running in `backup` mode.
